config/routes.rb
SampleApp::Application.routes.draw do

  resources :votes

  resources :games

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :games do
      post :vote, :on => :member
  end
 
  
  
  resources :sessions,      :only => [:new, :create, :destroy]
  resources :microposts,    :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]
  
  root :to => "pages#home"

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

end

app/models/game.rb
class Game < ActiveRecord::Base
	attr_accessible :name, :item1, :item2
	has_many :votes
end

app/controllers/games_controller.rb
class GamesController < ApplicationController



  # GET /games
  # GET /games.xml
  def index
    
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.xml
  def show
    
    @game = Game.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @game }
    end
  end


  
  # GET /games/new
  # GET /games/new.xml
  def new
    @game = Game.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @game }
    end
  end
  


  # GET /games/1/edit
  def edit
    @game = Game.find(params[:id])
  end

  # POST /games
  # POST /games.xml
  def create
    @game = Game.new(params[:game])

    respond_to do |format|
      if @game.save
        format.html { redirect_to(@game, :notice => 'Game was successfully created.') }
        format.xml  { render :xml => @game, :status => :created, :location => @game }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @game.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /games/1
  # PUT /games/1.xml
  def update
    @game = Game.find(params[:id])

    respond_to do |format|
      if @game.update_attributes(params[:game])
        format.html { redirect_to(@game, :notice => 'Game was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @game.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.xml
  def destroy
    @game = Game.find(params[:id])
    @game.destroy

    respond_to do |format|
      format.html { redirect_to(games_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :item1 %><br />
    <%= f.text_area :item1 %>
  </div>
  <div class="field">
    <%= f.label :item2 %><br />
    <%= f.text_area :item2 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<!--<h1>Listing games</h1>

<table>
  <tr>
    <th>Item1</th>
    <th>Game 1 Votes</th>
    <th>Vote</th>
    <th>Item 2</th>
    <th>Games 2 Votes</th>
    <th>Vote</th>
    <th></th>
  </tr>

<% @games.each do |game| %>
  <tr>
    <td><%= game.item1 %>
     <td><%= game.votes1 %></td>
</td>
    <td><%= game.item2 %></td>
    <td><%= game.votes2 %></td>
<% end %>
</table>

<br />--!>
<style tye="text/css">
.team{
	padding-top:70px;
}
.team2{
	padding-top:70px;
}
table{
	padding-top:50px;
}
</style>
<div class="container">
<table> 
        <thead> 
          <tr> 
            <th>Team 1</th> 
            <th>Votes</th> 
            <th>Team 2</th> 
            <th>Votes</th> 
          </tr> 
        </thead> 
        <tbody> 
          <tr> 
          <% @games.each do |game| %>
            <td><%= game.item1 %>
</td> 
            <td><%= game.votes1 %></td> 
            <td><%= game.item2 %></td> 
            <td><%= game.votes2 %></td> 
          </tr> 
        	<% end %>
        </tbody> 
      </table> 
</div>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<style type="text/css">
.game{
	padding-top:70px;
}
</style>
<div class="game">
<p id="notice"><%= notice %></p>

<p>
  <b>Item1:</b>
  <%= @game.item1 %>
  <%= @game.votes1 %>
</p>

<p>
  <b>Item2:</b>
  <%= @game.item2 %>
  <%= @game.votes2 %>
</p>


<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>
</div>